### ISSUE TITLE
question about Specifications this project

### ISSUE THREAD

**Issue by mohammada315** [ArduPilot/ArduRemoteID#3]
dear ardupilot Developers
Is it possible to see all the drones around with this program?
Similar to ADS B

**Comment by davidbuzz** [comment]
"RemoteID" is currently trying to be mandated in many countries, most specifically the USA right now.  This repo is a work-in-progress toward making ArduPilot interoperate with this, where its mandated by law.  https://en.wikipedia.org/wiki/Remote_ID

**Comment by mohammada315** [comment]
I did not understand exactly the function and working method of this repository
