### ISSUE TITLE
PIN_STATUS_LED broken with 1.9 update

### ISSUE THREAD

**Issue by sborenstein-ift** [ArduPilot/ArduRemoteID#62]
Good news, the WS2812 LED works. The "dumb LED" output is now broken.

**Comment by BluemarkInnovations** [comment]
Yes I noticed. I did some testing, but I don't have the final solution. The LED works (but flashes if it is not connected to the Cube) by adding this line `pinMode(PIN_STATUS_LED, OUTPUT);` to the setup function of RemoteIDModule.ino. It looks as if the init function is not properly called.

**Comment by BluemarkInnovations** [comment]
Is fixed in 1.10, so this issue can be closed.

**Comment by tridge** [comment]
fixed
